openapi: 3.0.0
info:
  title: Keboola OAuth Service
  version: '1.0.0'
  contact:
    email: devel@keboola.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

paths:
  /authorize/{componentId}:
    post:
      summary: Authorization init
      operationId: authorizeInit
      tags:
        - Authorize
      description: |
        Call the endpoint to initiate the authorization process. It starts the authorization sessions and redirects
        client to the OAuth provider.
      parameters:
        - in: path
          name: componentId
          schema:
            type: string
          required: true
          description: Component ID
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - id
                - authorizedFor
                - token
                - returnUrl
              properties:
                id:
                  type: string
                  description: Authorization ID
                authorizedFor:
                  type: string
                  description: Authorization description
                token:
                  type: string
                  description: Storage token of the requester
                returnUrl:
                  type: string
                  description: URL where to redirect the client after authorization
                appKey:
                  type: string
                  nullable: true
                  description: Custom application key
                appSecret:
                  type: string
                  nullable: true
                  description: Custom application secret
                authUrl:
                  type: string
                  nullable: true
                  description: Custom authorization URL
                tokenUrl:
                  type: string
                  nullable: true
                  description: Custom token URL
                branchId:
                  type: string
                  nullable: true
                  description: |
                    ID of the branch where the credentials should live. If not specified, the credentials will be
                    considered as project-wide.

                    The property is not required for now, to keep compatibility with existing clients. But it will be
                    required in the future (but still nullable), to ensure the client has considered if they want to
                    create project-wide or branch-specific credentials.
      responses:
        '302':
          description: Redirect to OAuth provider
          headers:
            Location:
              description: URL to follow to authorize the component
              schema:
                type: string
                format: url
        '400':
          $ref: '#/components/responses/400_BadRequest'
        '422':
          $ref: '#/components/responses/422_UnprocessableEntity'

  /authorize/{componentId}/callback:
    get:
      summary: Authorization callback
      operationId: authorizeCallback
      tags:
        - Authorize
      description: |
        The endpoint is called by OAuth provider after the authorization process is finished. It uses parameters passed
        in query to retrieve the access token and stores the authorization. Finally it redirects the client back to the
        return URL.
      parameters:
        - in: path
          name: componentId
          schema:
            type: string
          required: true
          description: Component ID
      responses:
        '302':
          description: Redirect client back to Keboola
          headers:
            Location:
              schema:
                type: string
                format: url
        '400':
          $ref: '#/components/responses/400_BadRequest'

  /credentials:
    get:
      summary: Credentials list
      operationId: credentialsList
      tags:
        - Credentials
      description: |
        Returns list of component credentials.
      security:
        - StorageToken: []
      parameters:
        - in: query
          name: componentId
          schema:
            type: string
          description: Component ID
        - in: query
          name: branchId
          schema:
            type: string
          description: |
            Branch ID
            
            Use value `null` to get credentials without branchId.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Credentials'
        '401':
          $ref: '#/components/responses/401_Unauthorized'
        '403':
          $ref: '#/components/responses/403_Forbidden'

  /credentials/{componentId}:
    get:
      summary: Component credentials list
      operationId: componentCredentialsList
      tags:
        - Credentials
      description: |
        Returns list of component credentials.
      security:
        - StorageToken: []
      parameters:
        - in: path
          name: componentId
          schema:
            type: string
          required: true
          description: Component ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Credentials'
        '401':
          $ref: '#/components/responses/401_Unauthorized'
        '403':
          $ref: '#/components/responses/403_Forbidden'
    post:
      summary: Create credentials
      operationId: componentCredentialsCreate
      tags:
        - Credentials
      description: |
        Call the endpoint to create new credentials for given component.
      security:
        - StorageToken: []
      parameters:
        - in: path
          name: componentId
          schema:
            type: string
          required: true
          description: Component ID
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - id
                - authorizedFor
                - '#data'
              properties:
                id:
                  type: string
                  description: Credentials ID
                authorizedFor:
                  type: string
                  description: Authorization description
                '#data':
                  type: string
                  description: Encrypted data, e.g. OAuth token
                branchId:
                  type: string
                  nullable: true
                  description: |
                    ID of the branch where the credentials should live. If not specified, the credentials will be
                    considered as project-wide.

                    The property is not required for now, to keep compatibility with existing clients. But it will be
                    required in the future (but still nullable), to ensure the client has considered if they want to
                    create project-wide or branch-specific credentials.
      responses:
        '201':
          description: Credentials created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credentials'
        '400':
          $ref: '#/components/responses/400_BadRequest'
        '404':
          $ref: '#/components/responses/404_NotFound'
        '422':
          $ref: '#/components/responses/422_UnprocessableEntity'

  /credentials/{componentId}/{name}:
    get:
      summary: Credentials detail
      operationId: credentialsDetail
      tags:
        - Credentials
      description: |
        Returns the credentials detail.
      security:
        - StorageToken: []
      parameters:
        - in: path
          name: componentId
          schema:
            type: string
          required: true
          description: Component ID
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: Credentials name (authorization ID)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credentials'
        '401':
          $ref: '#/components/responses/401_Unauthorized'
        '403':
          $ref: '#/components/responses/403_Forbidden'

    delete:
      summary: Delete credentials
      operationId: credentialsDelete
      tags:
        - Credentials
      description: |
        Delete existing credentials.
      security:
        - StorageToken: []
      parameters:
        - in: path
          name: componentId
          schema:
            type: string
          required: true
          description: Component ID
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: Credentials name (authorization ID)
      responses:
        '204':
          description: Credentials deleted
        '401':
          $ref: '#/components/responses/401_Unauthorized'
        '404':
          $ref: '#/components/responses/404_NotFound'

  /manage:
    get:
      summary: List consumers
      operationId: consumersList
      tags:
        - Consumers
      description: |
        Returns list of all registered consumers.
      security:
        - ManageToken: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Consumer'
        '401':
          $ref: '#/components/responses/401_Unauthorized'
    post:
      summary: Create consumer
      operationId: consumerCreate
      tags:
        - Consumers
      description: |
        Register a new OAuth consumer (component).
      security:
        - ManageToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - componentId
                - friendlyName
                - oauthVersion
                - authUrl
                - tokenUrl
                - appKey
                - appSecret
              properties:
                componentId:
                  type: string
                friendlyName:
                  type: string
                oauthVersion:
                  type: string
                authUrl:
                  type: string
                tokenUrl:
                  type: string
                requestTokenUrl:
                  type: string
                  nullable: true
                appKey:
                  type: string
                appSecret:
                  type: string
                restrictCustomAuth:
                  type: boolean
      responses:
        '201':
          description: Consumer created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consumer'
        '401':
          $ref: '#/components/responses/401_Unauthorized'
        '422':
          $ref: '#/components/responses/422_UnprocessableEntity'

  /manage/{componentId}:
    get:
      summary: Consumer detail
      operationId: consumerDetail
      tags:
        - Consumers
      description: |
        Returns the consumer detail for given component.
      security:
        - ManageToken: []
      parameters:
        - in: path
          name: componentId
          schema:
            type: string
          required: true
          description: Component ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consumer'
        '401':
          $ref: '#/components/responses/401_Unauthorized'
        '404':
          $ref: '#/components/responses/404_NotFound'
    patch:
      summary: Update consumer
      operationId: consumerUpdate
      tags:
        - Consumers
      description: |
        Update an existing consumer. All fields are optional.
      security:
        - ManageToken: []
      parameters:
        - in: path
          name: componentId
          schema:
            type: string
          required: true
          description: Component ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                friendlyName:
                  type: string
                  nullable: true
                authUrl:
                  type: string
                  nullable: true
                tokenUrl:
                  type: string
                  nullable: true
                requestTokenUrl:
                  type: string
                  nullable: true
                appKey:
                  type: string
                  nullable: true
                appSecret:
                  type: string
                  nullable: true
                restrictCustomAuth:
                  type: boolean
                  nullable: true
      responses:
        '200':
          description: Consumer updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consumer'
        '401':
          $ref: '#/components/responses/401_Unauthorized'
        '404':
          $ref: '#/components/responses/404_NotFound'
        '422':
          $ref: '#/components/responses/422_UnprocessableEntity'
    delete:
      summary: Delete consumer
      operationId: consumerDelete
      tags:
        - Consumers
      description: |
        Delete an existing consumer.
      security:
        - ManageToken: []
      parameters:
        - in: path
          name: componentId
          schema:
            type: string
          required: true
          description: Component ID
      responses:
        '204':
          description: Consumer deleted
        '401':
          $ref: '#/components/responses/401_Unauthorized'
        '404':
          $ref: '#/components/responses/404_NotFound'

  /health-check:
    get:
      summary: Health-check endpoint
      operationId: healthCheck
      tags:
        - Others
      description: |
        Checks the service is up & running.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  api:
                    type: string
                  documentation:
                    type: string
                    format: url
                example:
                  api: symfony-skeleton
                  documentation: http://localhost/docs/swagger.yaml

components:
  securitySchemes:
    StorageToken:
      type: apiKey
      in: header
      name: X-StorageApi-Token
    ManageToken:
      type: apiKey
      in: header
      name: X-KBC-ManageApiToken

  schemas:
    Error:
      type: object
      required:
        - error
        - code
        - exceptionId
        - status
      properties:
        error:
          type: string
        code:
          type: integer
        exceptionId:
          type: string
        status:
          enum: [error]
        context:
          type: object

    Consumer:
      type: object
      required:
        - componentId
        - friendlyName
        - oauthVersion
        - authUrl
        - tokenUrl
        - requestTokenUrl
        - appKey
        - appSecret
        - appSecretDocker
        - restrictCustomAuth
      properties:
        componentId:
          type: string
        friendlyName:
          type: string
        oauthVersion:
          type: string
        authUrl:
          type: string
        tokenUrl:
          type: string
        requestTokenUrl:
          type: string
          nullable: true
        appKey:
          type: string
        appSecret:
          type: string
        appSecretDocker:
          type: string
        restrictCustomAuth:
          type: boolean

    Credentials:
      type: object
      required:
          - id
          - branchId
          - authorizedFor
          - creator
          - created
          - oauthVersion
          - appKey
          - '#appSecret'
          - '#data'
      properties:
        id:
          type: string
        branchId:
          type: string
          nullable: true
        authorizedFor:
          type: string
        creator:
          type: object
          required:
            - id
            - description
          properties:
            id:
              type: string
            description:
              type: string
              nullable: true
        created:
          type: string
          format: date-time
        oauthVersion:
          type: string
        appKey:
          type: string
        '#appSecret':
          type: string
        '#data':
          type: string

  responses:
    400_BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    422_UnprocessableEntity:
      description: Unprocessable entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    401_Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    403_Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    404_NotFound:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
