openapi: 3.0.3
info:
  title: Encryption
  version: ''
  description: |-
    Encryption is part of the [Job Runner](https://developers.keboola.com/extend/docker-runner/) component. Job Runner
    is a Keboola service, that runs configurations of components as Keboola Connection jobs.
servers:
  - url: https://encryption.{stack}
    variables:
      stack:
        enum:
          - keboola.com
          - eu-central-1.keboola.com
          - north-europe.azure.keboola.com
          - europe-west2.gcp.keboola.com
          - europe-west3.gcp.keboola.com
          - us-east4.gcp.keboola.com
          - eu-west-1.aws.keboola.dev
          - east-us-2.azure.keboola-testing.com
          - us-central1.gcp.keboola.dev
        default: keboola.com
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: Index endpoint
      operationId: index
      tags:
        - Others
      description: |
        Returns basic information about the service.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - appName
                  - appVersion
                  - apiDocs
                properties:
                  appName:
                    type: string
                  appVersion:
                    type: string
                  apiDocs:
                    type: string
                    format: url
                example:
                  appName: encryption-api
                  appVersion: production-cc0b67a2e584003a7662ab7a3808867950338970.Release-92
                  apiDocs: https://encryption.keboola.com/docs/swagger.yaml

  /health-check:
    get:
      summary: Health-check endpoint
      operationId: healthCheck
      tags:
        - Others
      description: |
        Checks the service is up & running.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                properties:
                  status:
                    type: string
                    enum: [ok]
                example:
                  status: ok

  /encrypt:
    post:
      summary: Encrypt data
      operationId: encryptData
      tags:
        - Encrypt
      description: Encrypts a string or a JSON
      parameters:
        - name: componentId
          in: query
          description: Keboola Connection Component Id
          required: false
          schema:
            type: string
          examples:
            id:
              value: 'keboola.ex-example'
        - name: projectId
          in: query
          description: Keboola Connection Project Id
          required: false
          schema:
            type: string
          examples:
            id:
              value: '1234'
        - name: configId
          in: query
          description: Keboola Connection Configuration Id (when used, `projectId` must also be specified)
          required: false
          schema:
            type: string
          examples:
            id:
              value: 'my-config-id'
        - name: branchType
          in: query
          description: Development branch type, either 'default' for production branch or 'dev' for development branch.
          required: false
          schema:
            type: string
            enum: ['default', 'dev']
          examples:
            id:
              value: 'default'
      requestBody:
        content:
          application/json:
            example:
              '#test': MyValueToBeEncrypted
          text/plain:
            example: KBC::ProjectSecure::ENCODEDSTRING==
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                example:
                  '#test': KBC::ProjectSecure::xxxxxx
            text/plain:
              schema:
                type: object
                items:
                  type: string
                example: KBC::ProjectSecure::ENCODEDSTRING==

  /migrate-configuration:
    post:
      summary: Migrate configuration
      operationId: migrateConfiguration
      tags:
        - Migrate
      description: |
        Migrates configuration from the source to the destination project.
        Every encrypted key is decrypted and re-encrypted for the destination stack.
      security:
        - configMigration: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MigrateConfigurationPayload'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MigrateConfigurationSucceeded'
        '400':
          $ref: '#/components/responses/400_BadRequest'
        '401':
          $ref: '#/components/responses/401_Unauthorized'
        '404':
          $ref: '#/components/responses/404_NotFound'
        '422':
          $ref: '#/components/responses/422_UnprocessableEntity'

components:
  securitySchemes:
    configMigration:
      type: apiKey
      in: header
      name: X-KBC-ManageApiToken
      description: Assigned user must have `can-migrate-secrets` feature

  schemas:
    Error:
      type: object
      required:
        - error
        - code
        - exceptionId
        - status
      properties:
        error:
          type: string
        code:
          type: integer
        exceptionId:
          type: string
        status:
          enum: [error]
        context:
          type: object

    MigrateConfigurationPayload:
      type: object
      required:
        - sourceStorageApiToken
        - destinationStack
        - destinationStorageApiToken
        - componentId
        - configId
        - branchId
      properties:
        sourceStorageApiToken:
          type: string
          description: Storage API token for source stack
        destinationStack:
          enum:
            - connection.europe-west3.gcp.keboola.com
            - connection.us-east4.gcp.keboola.com
            - connection.europe-west2.gcp.keboola.com
            - connection.us-central1.gcp.keboola.dev
        destinationStorageApiToken:
          type: string
          description: Storage API token for destination stack
        componentId:
          type: string
          description: Component ID to migrate
        configId:
          type: string
          description: Configuration ID to migrate
        branchId:
          type: string
          description: Branch ID to migrate from

    MigrateConfigurationSucceeded:
      type: object
      items:
        type: string
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            destinationStack:
              type: string
            componentId:
              type: string
            configId:
              type: string
            branchId:
              type: string
        warnings:
          items:
            type: string
      example:
        message: Configuration with ID "123" successfully migrated to stack "us-east4.gcp.keboola.com".
        data:
          destinationStack: us-east4.gcp.keboola.com
          componentId: 'keboola.ex-gcalendar'
          configId: '123'
          branchId: '1'
        warnings:
          - Cannot migrate OAuth credentials of component "keboola.ex-gcalendar".

  responses:
    400_BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    422_UnprocessableEntity:
      description: Unprocessable entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    401_Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    403_Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    404_NotFound:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
