openapi: 3.0.0
info:
  title: AI Actions service API
  version: 1.0.0
  contact:
    email: devel@keboola.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
tags:
- name: service
paths:
  /:
    get:
      summary: Service index
      operationId: ''
      tags:
      - service
      description: Get basic service information and API documentation link
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/handlers.IndexResponse'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-StorageApi-Token
