openapi: 3.2.0
info:
  contact:
    email: support@keboola.com
    name: Keboola Support
    url: https://help.keboola.com/management/support/
  description: A service for managing and executing SQL query jobs with support for transactional operations and job status tracking.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Query Service API
  version: 1.0.0
servers:
- url: https://query.north-europe.azure.keboola.com/
tags:
- name: service
paths:
  /:
    get:
      summary: Service index
      operationId: ''
      tags:
      - service
      description: Get basic service information and API documentation link
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/handlers.IndexResponse'
components:
  securitySchemes:
    StorageApiToken:
      type: apiKey
      name: X-StorageAPI-Token
      in: header
